name: Playwright Tests + Allure Report

on:
  push:
    branches: [ main, master, test-01-allure ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      TEST_EMAIL: ${{ secrets.USER_EMAIL }}
      TEST_PASSWORD: ${{ secrets.USER_PASSWORD }}


    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Generate Allure report
        run: npx allure generate allure-results -o allure-report --clean

      - name: Upload Allure artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4